### ISSUE TITLE
Code Samples?

### ISSUE THREAD

**Issue by xiaoyongzhu** [srp-31/Object-Detection-Data-Augmentation#1]
Hi,

Thanks for this repository, looks like it is very helpful for my OD task! One quick suggestion is that to add a link to the file (CreateSamples.py) to help people get started:)

**Comment by srp-31** [comment]
Hi,

Thanks for you sugeestion. I think its a nice idea. You mean adding it to the readme file? 

Update: I made some changes so if this was your suggestion I can close the issue :)
