### ISSUE TITLE
What do the parameters in the file mean?

### ISSUE THREAD

**Issue by lfrcoder** [srp-31/Object-Detection-Data-Augmentation#3]
hi，
Thank you for your code，Because i am a newcomer to this field,
I have a question here.
What do the parameters in the parameters.cofig file mean?Can you make a simple explanation in the file?
thank you very much！！！

**Comment by srp-31** [comment]
Hello, 

I tried to name the parameters to implicitly explain their meaning. The variable wiht 'Prob' (ex:GausNoiseProb) attached to its name indicates the probablity of the paritcular transform. More info I have explained in the Readme file. The maxXangle,maxYangle,maxZangle indicate the max perspective transform about each axes. The maxAngleAffine is the maximum angle for affine rotation about Z axis. Hope these answer your doubts.

**Comment by srp-31** [comment]
Closing this issue hoping that the doubts are resolved. Goodluck.
