### ISSUE TITLE
PNG transparency

### ISSUE THREAD

**Issue by ClementDardenne** [srp-31/Object-Detection-Data-Augmentation#4]
Hi,

First, thanks for this project which could be of great help for me !

I was just trying to adapt the code to be able to add an object to the background of the scene while the object is a png image with transparent background. By doing this, we get rid of the background of the object and we can add it perfectly in the background of the scene. For now, you are only using .jpg image (so no transparency) and you remove the background (black/white) with a threshold in Parameters (bgColor/bgThresh), which doesn't remove completely the background most of the time.

I didn't have the time to read your code in details, but I will probably find a solution later. I just want to know if you see a quick trick to do what I want.

Thanks in advance !

**Comment by srp-31** [comment]
Hi Clément,

Thanks fory your interest and valuable feedback. A quick search suggested that opencv usually doesnt support this utility of removing the alpha background but apparently there are other solutions. I am currently working to correct some things with the package in its current state so will not be look into the issue. But please feel free to add a relevant link or a pull request for adding this functionality.  And also you are right about the bg color bg thresh approach. It was an idea I borrowed form OpenCV creatsamples applciation for Haar classifier. It was sufficient for my use as such. Later depending on available time I would like to work on a better idea.

thanks 
shreeraman

**Comment by srp-31** [comment]
Hi Clement,

Maybe the link below is helpful.
https://stackoverflow.com/questions/38627870/how-to-paste-a-png-image-with-transparency-to-another-image-in-pil-without-white/38629258

regards
shreeraman

**Comment by ClementDardenne** [comment]
Hi,

I finally implemented this solution (based on alpha channel) : 
https://stackoverflow.com/questions/41508458/python-opencv-overlay-an-image-with-transparency

Unfortunately, it would take me too much time to implement it in your project, that I don't have. That's why I realized my own script (way more simplistic that your project) that just add an object to a background with rotation, size, and noise.

Thank you for your responsiveness and help.

Clément

**Comment by srp-31** [comment]
Hi Clément, 

Thank you for the link. This might be useful for other interested people. I was thinking my project is simplistic too but I think my code is always simple for me after I have written it. I would love to have a look at your approach and maybe modify my work too so that its simple for other users. Kindly let me know if you plan to make your work public or have some suggestions for my project.  

shreeraman
