### ISSUE TITLE
Is there already some augmentation techniques implemented in YOLO ?

### ISSUE THREAD

**Issue by Rahul-Venugopal** [srp-31/Object-Detection-Data-Augmentation#7]
Is there already some augmentation techniques implemented in YOLO ?

Actually I am not able to understand the concept of Data Augmentation for YOLO , where will be the Augmentation done in the pipeline? Do we have to do data augmentation on the training image before annotating it or is it after annotation ?

It would be nice if I can get some help to understand the concept.

Thanks 
Rahul

**Comment by srp-31** [comment]
Hello,

Sorry for the delayed reply. Simply augmentations(like horiyontal flipping, scaling etc.) are definitely part of the yolo training pipline. These are for common class of objects like animals, cars etc for which horizontal flipping makes sense. However for some special cases like in my case (hands in wild), it made sense for me to make additional augmentaion with rotation, noise addition etc. Data augmentaion and annotation go hand in hand. Generally it would be wise to automate data annotation based on the augmentation performed. Hope the reply helps inspite of the delay. Goodluck!
