### ISSUE TITLE
geting Bounding boxes from rotate_3d-master

### ISSUE THREAD

**Issue by kerolos** [srp-31/Object-Detection-Data-Augmentation#8]
is there any way to generate  Bounding boxes from rotate_3d-master ?
I tried to use the equation from OpenCV that provided in this link:  https://docs.opencv.org/2.4/modules/imgproc/doc/geometric_transformations.html 

![image](https://user-images.githubusercontent.com/3300016/53943841-48272680-40be-11e9-9deb-dbba7c02f8b1.png)
but it only works when using gamma, dx, and dz (rotation around the z axis,translation along the x axis, translation along the y axis ).

**Comment by srp-31** [comment]
Hi there,

As far as I see there should be no problem except when the transformed cordinates are outside the destination image size. Could you provide more details? If you have already figured out the source and the solution , please do comment here so that it could help other. thanks.

**Comment by kerolos** [comment]
Hello @srp-31 :+1: 
thanks for your reply. now I can rotate and translate any point in 3d by using this function from OpenCV perspectiveTransform, which equivalent to this function in image processing  (warpPerspective).

**Comment by srp-31** [comment]
Hey kerolos,

Thanks for the reply! I would have done the same in your.
