### ISSUE TITLE
ValueError: Range cannot be empty (low >= high) unless no samples are taken

### ISSUE THREAD

**Issue by yuki4ghub15** [srp-31/Object-Detection-Data-Augmentation#9]
Hi, While using CreateSamples.py in python 2.7 , i received the following issues. Do you have any solution. 

File "mtrand.pyx", line 992, in mtrand.RandomState.randint
ValueError: Range cannot be empty (low >= high) unless no samples are taken

**Comment by PhilipsKoshy** [comment]
In the Parameters.config file, set backgroundFilePath =./Data/background/small to backgroundFilePath =./Data/background
I think they renamed the "small" folder to "original". 

Another mistake, I noticed is - they don't have an empty file __init__.py in the rotate_3D-Master folder. This was resulting in module load error. So, we need to add this empty file as well.

**Comment by giosullutrone** [comment]
Late to the party but just did a pull request addressing these issues.

**Comment by srp-31** [comment]
Thanks @SirCleric SirCleric for fixing issues identified @PhilipsKoshy . @yuki4ghub15 I am not sure of this issue. I would also have to search online for a fix and cant remember a solution from the top of my head. I currently dont have the capacity to check it. Hope you are / were able to find a work around. I am closing the issue but if its really a huge trouble feel free to raise it again and I can look into it over the weekend.
